//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctaShape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_RequestDetail
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public string Account_No { get; set; }
        public string Customer_Name { get; set; }
        public string EmbossName { get; set; }
        public Nullable<int> Request_Id { get; set; }
        public string Created_By { get; set; }
        public string Approved_By { get; set; }
        public Nullable<int> Card_RequestId { get; set; }
        public Nullable<int> Card_ReceivedId { get; set; }
        public string Branch_Code { get; set; }
        public string Card_Number { get; set; }
        public Nullable<System.DateTime> Delivered_Date { get; set; }
    
        public virtual Card_Received Card_Received { get; set; }
        public virtual Card_Requested Card_Requested { get; set; }
        public virtual Card_RequestType Card_RequestType { get; set; }
    }
}
