//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctaShape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_Requested
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card_Requested()
        {
            this.Card_Received = new HashSet<Card_Received>();
            this.Card_RequestDetail = new HashSet<Card_RequestDetail>();
        }
    
        public int Request_Id { get; set; }
        public Nullable<System.DateTime> Card_RequestDate { get; set; }
        public Nullable<System.DateTime> Request_StardDate { get; set; }
        public Nullable<System.DateTime> Request_EndDate { get; set; }
        public Nullable<int> Total_Cards { get; set; }
        public string Request_By { get; set; }
        public Nullable<bool> Is_Received { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card_Received> Card_Received { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card_RequestDetail> Card_RequestDetail { get; set; }
    }
}
