//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctaShape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_Received
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card_Received()
        {
            this.Card_RequestDetail = new HashSet<Card_RequestDetail>();
        }
    
        public int Received_Id { get; set; }
        public Nullable<System.DateTime> Received_Date { get; set; }
        public Nullable<int> Card_RequestId { get; set; }
        public Nullable<int> Cards_Received { get; set; }
        public string Received_By { get; set; }
        public Nullable<bool> IsPin_Received { get; set; }
    
        public virtual Card_Requested Card_Requested { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card_RequestDetail> Card_RequestDetail { get; set; }
    }
}
