//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctaShape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_Activate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card_Activate()
        {
            this.Card_ReceivedDetails = new HashSet<Card_ReceivedDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Activate_Date { get; set; }
        public Nullable<System.DateTime> Activate_Start { get; set; }
        public Nullable<System.DateTime> Activate_End { get; set; }
        public Nullable<int> No_ofCards { get; set; }
        public string Activated_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card_ReceivedDetails> Card_ReceivedDetails { get; set; }
    }
}
