//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctaShape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_ReceivedDetails
    {
        public int Received_Id { get; set; }
        public string Branch_Code { get; set; }
        public string Account_No { get; set; }
        public string Card_No { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<System.DateTime> Delivered_Date { get; set; }
    
        public virtual Card_Received Card_Received { get; set; }
    }
}
