//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctaShape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketComment()
        {
            this.TicketImage = new HashSet<TicketImage>();
        }
    
        public int id { get; set; }
        public int TicketId { get; set; }
        public string TicketComment1 { get; set; }
        public string CommentBy { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketImage> TicketImage { get; set; }
    }
}
