//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctaShape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketImage
    {
        public int ImageId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> TicketCommentId { get; set; }
        public string Url { get; set; }
        public string ImageOn { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual TicketComment TicketComment { get; set; }
    }
}
