//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctaShape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketComment = new HashSet<TicketComment>();
            this.TicketImage = new HashSet<TicketImage>();
        }
    
        public int id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> TicketPriorityId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> TicketStatusId { get; set; }
        public Nullable<bool> EditEnable { get; set; }
        public Nullable<System.DateTime> LastEditedOn { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public Nullable<int> Categoryid { get; set; }
        public string BranchCode { get; set; }
        public Nullable<int> AssignedTo { get; set; }
    
        public virtual TicketBranch TicketBranch { get; set; }
        public virtual TicketCategory TicketCategory { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketComment> TicketComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketImage> TicketImage { get; set; }
        public virtual TicketPriority TicketPriority { get; set; }
        public virtual TicketStatus TicketStatus { get; set; }
    }
}
