//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctaShape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginInfo
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string IPAddress { get; set; }
        public string HostAddress { get; set; }
    }
}
